name: Publish to Confluence
on: 
  - push
  - workflow_dispatch

env:
  SLACK_CHANNEL_ID: C06B0NNMRCL

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          slack-message: |
            GitHub build result
            sdafsafsaf
            asdfgsdagfa
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      