on:
  pull_request:
    types:
      - closed

env:
  SLACK_CHANNEL_ID: C06B0NNMRCL

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          slack-message: |
            *Pull request #${{ github.event.pull_request.number }} got merged into the master* :white_check_mark:
            *Title:* ${{ github.event.pull_request.title }}
            *URL:* ${{ github.event.pull_request.html_url }}
            *Head Branch:* ${{ github.event.pull_request.head.ref }}
            *Author:* ${{ github.event.pull_request.user.login }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      