name: Check if top.sls file changed

on:
  workflow_dispatch:

jobs:
  run_shell_script:
    runs-on: ubuntu-latest

    env:
      ENV_VARIABLE_1: "Value1"
      ENV_VARIABLE_2: "Value2"
      # Add more environment variables as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: |
        # Navigate to the parent directory where the script is located
        cd ..

        # Execute the shell script with environmental variables
        ./script.sh

        # You can access the defined environment variables here as well
        echo "Environment Variable 1: $ENV_VARIABLE_1"
        echo "Environment Variable 2: $ENV_VARIABLE_2"
        # Add more commands as needed