name: Check if doc1.txt file changed

on:
  pull_request:
    paths:
      - 'doc1.txt'

jobs:
  check_file_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check if doc1.txt changed
      run: |
        if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -q '^doc1\.txt$'; then
          echo "The doc1.txt file has been changed."
          exit 0
        else
          echo "The doc1.txt file has not been changed."
          exit 1
        fi
