name: Check if top.sls file changed

on:
  pull_request:
    paths:
      - 'top.sls'

jobs:
  check_file_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2


    - name: Check PR Title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        if ! [[ $PR_TITLE =~ CM-[0-9]+ ]]; then
          echo "PR title does not match the required pattern 'CM-[0-9]+'"
          echo "Please update the PR title to match the required pattern."
          exit 1
        else
          echo "PR title matches the required pattern."
        fi
