name: Check if top.sls file changed

on:
  [workflow_dispatch, push]

jobs:
  run_shell_script:
    runs-on: ubuntu-latest

    env:
      ENV_VARIABLE_1: "Value1"
      ENV_VARIABLE_2: "Value2"
      # Add more environment variables as needed
    defaults:
      run:
        working-directory: ./.github/bin/
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github

    - name: Make the script files executable
      run: chmod +x script.sh

    - name: Run Shell Script
      run: |
        # Execute the shell script with environmental variables
        ./script.sh

