name: PR

on: [pull_request, workflow_dispatch]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin pull/${{ github.event.pull_request.number }}/head:pr
        git diff --name-only pr..HEAD > changed_files.txt
      shell: bash

    - name: Print changed files
      run: cat changed_files.txt
      shell: bash

    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}